development:
  adapter: postgresql
  encoding: utf8
  database: hubeert_development
  host: localhost
  pool: 5
  username: huBEERt
  password: "no_hubeert_moze_szocika"

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: hubeert_test
  host: localhost
  pool: 5
  username: huBEERt
  password: "no_hubeert_moze_szocika"

cucumber:
  <<: *TEST